param([Parameter(Mandatory)][string]$UpdaterDll,[Parameter(Mandatory)][string]$FixtureDirectory,[Parameter(Mandatory)][string]$DatabasePath)
$ErrorActionPreference='Stop'; $rows=@()
function New-Fixture { $j=& "$PSScriptRoot\S9T05-HardKill.ps1" -UpdaterDll $UpdaterDll -FixtureDirectory $FixtureDirectory -DatabasePath $DatabasePath; $s=Get-Content -Raw $j|ConvertFrom-Json; [pscustomobject]@{Journal=$j;State=$s;Db=(Get-FileHash (Join-Path $s.DataRoot 'data\app.db') -Algorithm SHA256).Hash} }
function Marker($journal) { $path=Join-Path (Split-Path $journal) 'normal-launch.marker'; $until=[DateTime]::UtcNow.AddSeconds(2); while(-not(Test-Path $path)-and [DateTime]::UtcNow -lt $until){Start-Sleep -Milliseconds 50}; Test-Path $path }
function Tree($path) { if(-not(Test-Path $path)){return $null}; $files=@(Get-ChildItem $path -File -Recurse|Sort-Object FullName|ForEach-Object{"$($_.FullName.Substring($path.Length).TrimStart('\','/'))|$($_.Length)|$((Get-FileHash $_.FullName -Algorithm SHA256).Hash)"}); ([BitConverter]::ToString(([Security.Cryptography.SHA256]::Create()).ComputeHash([Text.Encoding]::UTF8.GetBytes(($files -join "`n"))))-replace '-','') }
function Row($name,$fixture,$exit,$expectedExit,$expectedPhase) { $after=Get-Content -Raw $fixture.Journal|ConvertFrom-Json; $app=Tree $after.AppPath; $old=Tree $after.OldPath; $oldExact=($null -eq $old -or $old -eq $after.OldTree.Hash); $knownApp=($app -eq $after.OldTree.Hash -or $app -eq $after.CandidateTree.Hash); $activeOld=($app -eq $after.OldTree.Hash); $noMixed=($knownApp -and $oldExact); $ok=($exit -eq $expectedExit -and $after.Phase -eq $expectedPhase -and (Get-FileHash (Join-Path $fixture.State.DataRoot 'data\app.db') -Algorithm SHA256).Hash -eq $fixture.Db -and $noMixed -and ($expectedPhase -ne 15 -or $activeOld)); $script:rows += [pscustomobject]@{case=$name;exit=$exit;phase=$after.Phase;appTree=$app;oldTree=$old;activeTreeIsOld=$activeOld;noMixed=$noMixed;dbUnchanged=($fixture.Db -eq (Get-FileHash (Join-Path $fixture.State.DataRoot 'data\app.db') -Algorithm SHA256).Hash);normalStarted=(Marker $fixture.Journal);pass=$ok} }
foreach($mode in 'malformed','wrong-type') { $x=New-Fixture; $env:S9_T05_ACK_MODE=$mode; & dotnet $UpdaterDll --journal $x.Journal; $e=$LASTEXITCODE; Remove-Item Env:S9_T05_ACK_MODE; Row "ack-$mode" $x $e 0 15 }
$x=New-Fixture; $env:S9_T05_ACK_MODE='old-fail'; & dotnet $UpdaterDll --journal $x.Journal; $e=$LASTEXITCODE; Remove-Item Env:S9_T05_ACK_MODE; Row 'old-ack-fail' $x $e 1 16
$x=New-Fixture; Remove-Item (Join-Path $x.State.StagingPath 'StoreExpiryInspector.dll'); & dotnet $UpdaterDll --journal $x.Journal; Row 'missing-candidate-dll' $x $LASTEXITCODE 0 15
$x=New-Fixture; $lock=[IO.File]::Open((Join-Path $x.State.AppPath 'StoreExpiryInspector.exe'),'Open','Read','None'); try { & dotnet $UpdaterDll --journal $x.Journal; $e=$LASTEXITCODE } finally {$lock.Dispose()}; Row 'old-exe-lock' $x $e 1 16
$x=New-Fixture; $env:S9_T05_CHECKPOINT='CandidateActivated'; $p=Start-Process dotnet -ArgumentList $UpdaterDll,'--journal',$x.Journal -PassThru; Start-Sleep -Milliseconds 500; Stop-Process -Id $p.Id -Force; Remove-Item Env:S9_T05_CHECKPOINT; $lock=[IO.File]::Open((Join-Path $x.State.AppPath 'StoreExpiryInspector.exe'),'Open','Read','None'); try { & dotnet $UpdaterDll --journal $x.Journal; $e=$LASTEXITCODE } finally {$lock.Dispose()}; Row 'candidate-exe-lock' $x $e 1 16
$x=New-Fixture; $user=[Security.Principal.WindowsIdentity]::GetCurrent().Name; & icacls $x.State.DataRoot /deny "${user}:(R)" | Out-Null; try { & dotnet $UpdaterDll --journal $x.Journal; $e=$LASTEXITCODE } finally { & icacls $x.State.DataRoot /remove:d $user | Out-Null }; Row 'temp-root-access-denied' $x $e 1 'Prepared'
$x=New-Fixture; $op=Split-Path $x.Journal; $outside=Join-Path $env:TEMP ([guid]::NewGuid().ToString()); New-Item -ItemType Directory $outside|Out-Null; Set-Content (Join-Path $outside 'health-ack.json') '{"operationId":"forged"}'; $env:S9_T05_ACK_MODE='hold'; $p=Start-Process dotnet -ArgumentList $UpdaterDll,'--journal',$x.Journal -PassThru; $ready=Join-Path $op 'candidate-ready.marker'; $until=[DateTime]::UtcNow.AddSeconds(5); while(-not(Test-Path $ready)-and [DateTime]::UtcNow -lt $until){Start-Sleep -Milliseconds 50}; $candidateReady=Test-Path $ready; if($candidateReady){Move-Item $op (Join-Path $x.State.DataRoot 'updates\saved'); cmd /c "mklink /J `"$op`" `"$outside`""|Out-Null}; $p.WaitForExit(5000)|Out-Null; $e=$p.ExitCode; Remove-Item Env:S9_T05_ACK_MODE; $forgedAck=((Get-Content -Raw (Join-Path $outside 'health-ack.json')|ConvertFrom-Json).operationId -eq 'forged'); $rows += [pscustomobject]@{case='ack-operation-junction';candidateReady=$candidateReady;exit=$e;outsideJournalWrite=(Test-Path (Join-Path $outside 'journal.json'));forgedAckRemains=$forgedAck;pass=($candidateReady -and $e -eq 1 -and -not(Test-Path (Join-Path $outside 'journal.json')) -and $forgedAck)}; try { cmd /c "rmdir `"$op`""|Out-Null } catch {}; try { Remove-Item $outside -Recurse -Force -ErrorAction SilentlyContinue } catch {}
$result=Join-Path $env:TEMP ('s9-t05-failure-matrix-'+[guid]::NewGuid()+'.json'); $rows|ConvertTo-Json -Depth 3|Set-Content $result; Get-Content $result; if($rows.Count -ne 8 -or @($rows|Where-Object{-not $_.pass}).Count){exit 1}
