param([Parameter(Mandatory)] [string]$UpdaterDll, [Parameter(Mandatory)] [string]$FixtureDirectory, [Parameter(Mandatory)] [string]$DatabasePath, [string[]]$Checkpoints = @('MainExitRequested','MainExited','CandidateStaged','OldAppPreserved','SwitchStarted','CandidateActivated','CandidateStarted','WaitingForHealthAck','Committed'), [int]$Iterations = 3, [switch]$Rollback)
$ErrorActionPreference='Stop'; $rows=@()
foreach($checkpoint in $Checkpoints) { foreach($iteration in 1..$Iterations) {
  $journal = & "$PSScriptRoot\S9T05-HardKill.ps1" -UpdaterDll $UpdaterDll -FixtureDirectory $FixtureDirectory -DatabasePath $DatabasePath
  $db=(Join-Path ((Get-Content -Raw $journal|ConvertFrom-Json).dataRoot) 'data\app.db'); $dbBefore=(Get-FileHash $db -Algorithm SHA256).Hash
  $env:S9_T05_CHECKPOINT=$checkpoint
  $p=Start-Process dotnet -ArgumentList $UpdaterDll,'--journal',$journal -PassThru -RedirectStandardError "$journal.stderr"
  Start-Sleep -Milliseconds 500; $killed=-not $p.HasExited; if($killed){Stop-Process -Id $p.Id -Force}; Remove-Item Env:S9_T05_CHECKPOINT
  $out=& dotnet $UpdaterDll --journal $journal 2>&1; Start-Sleep -Milliseconds 100; $journalState=Get-Content -Raw $journal|ConvertFrom-Json; $active=Get-ChildItem $journalState.appPath -File -Recurse|Sort-Object FullName|ForEach-Object { "$($_.FullName.Substring($journalState.appPath.Length).TrimStart('\','/'))|$($_.Length)|$((Get-FileHash $_.FullName -Algorithm SHA256).Hash)" }; $activeHash=([BitConverter]::ToString(([Security.Cryptography.SHA256]::Create()).ComputeHash([Text.Encoding]::UTF8.GetBytes(($active -join "`n"))))-replace '-',''); $expectedHash=if($Rollback){$journalState.oldTree.hash}else{$journalState.candidateTree.hash}; $running=Get-Process -Id $journalState.candidatePid -ErrorAction SilentlyContinue; $expectedState=if($Rollback){15}else{10}; $normalMarker=Join-Path (Split-Path $journal) 'normal-launch.marker'; $deadline=[DateTime]::UtcNow.AddSeconds(2); while(-not (Test-Path $normalMarker) -and [DateTime]::UtcNow -lt $deadline){Start-Sleep -Milliseconds 50}; $normalStarted=Test-Path -LiteralPath $normalMarker; $packageExists=Test-Path (Join-Path (Split-Path $journal) 'candidate.zip'); $pass=($killed -and $LASTEXITCODE -eq 0 -and $journalState.phase -eq $expectedState -and $dbBefore -eq (Get-FileHash $db -Algorithm SHA256).Hash -and $activeHash -eq $expectedHash -and $null -eq $running -and $normalStarted -and ($packageExists -eq [bool]$Rollback)); $rows += [pscustomobject]@{checkpoint=$checkpoint;iteration=$iteration;killed=$killed;exit=$LASTEXITCODE;finalState=$journalState.phase;activeTreeHash=$activeHash;expectedTreeHash=$expectedHash;dbBefore=$dbBefore;dbAfter=(Get-FileHash $db -Algorithm SHA256).Hash;candidatePid=$journalState.candidatePid;candidatePidRunning=($null -ne $running);normalStarted=$normalStarted;candidatePackageExists=$packageExists;journal=$journal;pass=$pass}
} }
$result=Join-Path $env:TEMP ('s9-t05-hardkill-'+[guid]::NewGuid()+'.json'); $rows|ConvertTo-Json -Depth 3|Set-Content $result; Get-Content $result
