// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreExpiryInspector.Infrastructure;

#nullable disable

namespace StoreExpiryInspector.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260826123739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StoreExpiryInspector.Domain.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttentionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attention_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentArrivalQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_arrival_qty");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none")
                        .HasColumnName("current_stage");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date");

                    b.Property<int>("HandledAttentionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handled_attention_version");

                    b.Property<long?>("LastSeenImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_import_id");

                    b.Property<int>("LifecycleGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lifecycle_generation");

                    b.Property<int>("MaxArrivalQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_arrival_qty");

                    b.Property<DateOnly?>("NextTriggerDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_trigger_date");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("production_date");

                    b.Property<string>("ShelfLifeUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("D")
                        .HasColumnName("shelf_life_unit");

                    b.Property<int>("ShelfLifeValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shelf_life_value");

                    b.Property<string>("SourceDiscountReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_discount_reference");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_reason");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("stopped_at_utc");

                    b.Property<string>("TrackingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active")
                        .HasColumnName("tracking_status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_batches_expiry_date");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_batches_product_id");

                    b.HasIndex("ProductId", "ExpiryDate")
                        .IsUnique()
                        .HasDatabaseName("IX_batches_product_id_expiry_date")
                        .HasFilter("production_date IS NULL");

                    b.HasIndex("TrackingStatus", "NextTriggerDate")
                        .HasDatabaseName("IX_batches_tracking_status_next_trigger_date");

                    b.HasIndex("ProductId", "ProductionDate", "ExpiryDate")
                        .IsUnique()
                        .HasDatabaseName("IX_batches_product_id_production_date_expiry_date")
                        .HasFilter("production_date IS NOT NULL");

                    b.ToTable("batches", null, t =>
                        {
                            t.HasCheckConstraint("CK_batches_current_arrival_qty_nonnegative", "current_arrival_qty >= 0");

                            t.HasCheckConstraint("CK_batches_max_arrival_qty_nonnegative", "max_arrival_qty >= 0");

                            t.HasCheckConstraint("CK_batches_shelf_life_unit", "shelf_life_unit IN ('M', 'D', 'Y')");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("food")
                        .HasColumnName("category_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentBarcode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_barcode");

                    b.Property<string>("CurrentName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_name");

                    b.Property<int>("EffectiveStockQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_stock_qty");

                    b.Property<string>("EffectiveStockSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_stock_source");

                    b.Property<int>("ExcelStockQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excel_stock_qty");

                    b.Property<bool>("IsStockZeroTerminated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stock_zero_terminated");

                    b.Property<long?>("LastSeenImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_import_id");

                    b.Property<int>("LifecycleGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lifecycle_generation");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("food_v1")
                        .HasColumnName("policy_code");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasDatabaseName("IX_products_product_code");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_category_code_not_blank", "length(trim(category_code)) > 0");

                            t.HasCheckConstraint("CK_products_effective_stock_qty_nonnegative", "effective_stock_qty >= 0");

                            t.HasCheckConstraint("CK_products_excel_stock_qty_nonnegative", "excel_stock_qty >= 0");

                            t.HasCheckConstraint("CK_products_policy_code_not_blank", "length(trim(policy_code)) > 0");

                            t.HasCheckConstraint("CK_products_product_code_not_blank", "length(product_code) > 0 AND product_code = trim(product_code)");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Batch", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Product", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
