// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreExpiryInspector.Infrastructure;

#nullable disable

namespace StoreExpiryInspector.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260826170403_AddLifecycleEvents")]
    partial class AddLifecycleEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StoreExpiryInspector.Domain.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AutoStartEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_start_enabled");

                    b.Property<int>("ReminderMinuteOfDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(600)
                        .HasColumnName("reminder_minute_of_day");

                    b.HasKey("Id");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_settings_auto_start_enabled", "auto_start_enabled IN (0, 1)");

                            t.HasCheckConstraint("CK_settings_id_singleton", "id = 1");

                            t.HasCheckConstraint("CK_settings_reminder_minute_of_day_range", "reminder_minute_of_day BETWEEN 0 AND 1439");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.AppState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("LastNormalRunDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_normal_run_date");

                    b.Property<DateOnly?>("LastReminderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_reminder_date");

                    b.HasKey("Id");

                    b.ToTable("app_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_app_state_id_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.BackupRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("backup_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("verification_status");

                    b.HasKey("Id");

                    b.HasIndex("BackupType", "CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_backups_backup_type_created_at_utc_id");

                    b.ToTable("backups", null, t =>
                        {
                            t.HasCheckConstraint("CK_backups_backup_type", "backup_type IN ('auto', 'manual', 'pre_import', 'pre_restore', 'pre_upgrade')");

                            t.HasCheckConstraint("CK_backups_file_path_not_blank", "length(file_path) > 0 AND file_path = trim(file_path)");

                            t.HasCheckConstraint("CK_backups_sha256_lower_hex", "length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_backups_verification_status_not_blank", "length(verification_status) > 0 AND verification_status = trim(verification_status)");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttentionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attention_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentArrivalQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_arrival_qty");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none")
                        .HasColumnName("current_stage");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date");

                    b.Property<int>("HandledAttentionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handled_attention_version");

                    b.Property<long?>("LastSeenImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_import_id");

                    b.Property<int>("LifecycleGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lifecycle_generation");

                    b.Property<int>("MaxArrivalQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_arrival_qty");

                    b.Property<DateOnly?>("NextTriggerDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_trigger_date");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("production_date");

                    b.Property<string>("ShelfLifeUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("D")
                        .HasColumnName("shelf_life_unit");

                    b.Property<int>("ShelfLifeValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shelf_life_value");

                    b.Property<string>("SourceDiscountReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_discount_reference");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_reason");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("stopped_at_utc");

                    b.Property<string>("TrackingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active")
                        .HasColumnName("tracking_status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ProductId")
                        .HasName("AK_batches_id_product_id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_batches_expiry_date");

                    b.HasIndex("LastSeenImportId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_batches_product_id");

                    b.HasIndex("ProductId", "ExpiryDate")
                        .IsUnique()
                        .HasDatabaseName("IX_batches_product_id_expiry_date")
                        .HasFilter("production_date IS NULL");

                    b.HasIndex("TrackingStatus", "NextTriggerDate")
                        .HasDatabaseName("IX_batches_tracking_status_next_trigger_date");

                    b.HasIndex("ProductId", "ProductionDate", "ExpiryDate")
                        .IsUnique()
                        .HasDatabaseName("IX_batches_product_id_production_date_expiry_date")
                        .HasFilter("production_date IS NOT NULL");

                    b.ToTable("batches", null, t =>
                        {
                            t.HasCheckConstraint("CK_batches_current_arrival_qty_nonnegative", "current_arrival_qty >= 0");

                            t.HasCheckConstraint("CK_batches_max_arrival_qty_nonnegative", "max_arrival_qty >= 0");

                            t.HasCheckConstraint("CK_batches_shelf_life_unit", "shelf_life_unit IN ('M', 'D', 'Y')");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ImportIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FieldName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("field_name");

                    b.Property<long>("ImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_id");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("issue_type");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_number");

                    b.Property<string>("SafeSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("safe_summary");

                    b.HasKey("Id");

                    b.HasIndex("ImportId", "RowNumber", "Id")
                        .HasDatabaseName("IX_import_issues_import_id_row_number_id");

                    b.ToTable("import_issues", null, t =>
                        {
                            t.HasCheckConstraint("CK_import_issues_issue_type_not_blank", "length(issue_type) > 0 AND issue_type = trim(issue_type)");

                            t.HasCheckConstraint("CK_import_issues_row_number_positive", "row_number IS NULL OR row_number > 0");

                            t.HasCheckConstraint("CK_import_issues_safe_summary_not_blank", "length(safe_summary) > 0 AND safe_summary = trim(safe_summary)");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ImportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BatchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_count");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<bool>("IsUndone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_undone");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issue_count");

                    b.Property<int>("NewBatchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_batch_count");

                    b.Property<int>("NewProductCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_product_count");

                    b.Property<int>("NewTaskProductCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_task_product_count");

                    b.Property<DateTime>("ParsedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_at_utc");

                    b.Property<string>("PreImportSnapshotPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("pre_import_snapshot_path");

                    b.Property<int>("ProductCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_count");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_name");

                    b.Property<string>("SourceFileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UndoneAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("undone_at_utc");

                    b.Property<int>("UnsupportedCategoryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unsupported_category_count");

                    b.Property<int>("UpdatedBatchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_batch_count");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileSha256")
                        .HasDatabaseName("IX_imports_source_file_sha256");

                    b.HasIndex("Status", "ConfirmedAtUtc", "Id")
                        .HasDatabaseName("IX_imports_status_confirmed_at_utc_id");

                    b.ToTable("imports", null, t =>
                        {
                            t.HasCheckConstraint("CK_imports_batch_count_nonnegative", "batch_count >= 0");

                            t.HasCheckConstraint("CK_imports_issue_count_nonnegative", "issue_count >= 0");

                            t.HasCheckConstraint("CK_imports_new_batch_count_nonnegative", "new_batch_count >= 0");

                            t.HasCheckConstraint("CK_imports_new_product_count_nonnegative", "new_product_count >= 0");

                            t.HasCheckConstraint("CK_imports_new_task_product_count_nonnegative", "new_task_product_count >= 0");

                            t.HasCheckConstraint("CK_imports_product_count_nonnegative", "product_count >= 0");

                            t.HasCheckConstraint("CK_imports_source_file_name_not_blank", "length(source_file_name) > 0 AND source_file_name = trim(source_file_name)");

                            t.HasCheckConstraint("CK_imports_source_file_sha256_lower_hex", "length(source_file_sha256) = 64 AND source_file_sha256 NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_imports_status_not_blank", "length(status) > 0 AND status = trim(status)");

                            t.HasCheckConstraint("CK_imports_undone_fields", "(is_undone = 0 AND undone_at_utc IS NULL) OR (is_undone = 1 AND undone_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("CK_imports_unsupported_category_count_nonnegative", "unsupported_category_count >= 0");

                            t.HasCheckConstraint("CK_imports_updated_batch_count_nonnegative", "updated_batch_count >= 0");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ImportWorkbook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content");

                    b.Property<long>("ImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("saved_at_utc");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.HasKey("Id");

                    b.HasIndex("ImportId")
                        .IsUnique()
                        .HasDatabaseName("IX_import_workbooks_import_id");

                    b.ToTable("import_workbooks", null, t =>
                        {
                            t.HasCheckConstraint("CK_import_workbooks_content_not_empty", "length(content) > 0");

                            t.HasCheckConstraint("CK_import_workbooks_original_file_name_not_blank", "length(original_file_name) > 0 AND original_file_name = trim(original_file_name)");

                            t.HasCheckConstraint("CK_import_workbooks_sha256_lower_hex", "length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Inspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BarcodeSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode_snapshot");

                    b.Property<DateOnly>("CheckDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_date");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("inspector_name");

                    b.Property<string>("ProductCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code_snapshot");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductNameSnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name_snapshot");

                    b.Property<string>("StageSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("stage_snapshot");

                    b.Property<int>("StockQtySnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_qty_snapshot");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ProductId")
                        .HasName("AK_inspections_id_product_id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_inspections_task_id");

                    b.HasIndex("TaskId", "ProductId");

                    b.ToTable("inspections", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspections_inspector_name_not_blank", "length(inspector_name) > 0 AND inspector_name = trim(inspector_name)");

                            t.HasCheckConstraint("CK_inspections_product_code_snapshot_not_blank", "length(product_code_snapshot) > 0 AND product_code_snapshot = trim(product_code_snapshot)");

                            t.HasCheckConstraint("CK_inspections_stage_snapshot", "stage_snapshot IN ('discount_50', 'discount_20', 'withdraw', 'expired')");

                            t.HasCheckConstraint("CK_inspections_stock_qty_snapshot_nonnegative", "stock_qty_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionDraft", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CheckDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InspectorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("inspector_name");

                    b.Property<string>("InvalidReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("invalid_reason");

                    b.Property<DateTime?>("InvalidatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("invalidated_at_utc");

                    b.Property<bool>("IsInvalid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_invalid");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "TaskId")
                        .HasName("AK_drafts_id_task_id");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_drafts_task_id");

                    b.ToTable("drafts", null, t =>
                        {
                            t.HasCheckConstraint("CK_drafts_is_invalid", "is_invalid IN (0, 1)");

                            t.HasCheckConstraint("CK_drafts_validity_fields", "(is_invalid = 0 AND invalid_reason IS NULL AND invalidated_at_utc IS NULL) OR (is_invalid = 1 AND invalid_reason IS NOT NULL AND length(trim(invalid_reason)) > 0 AND invalidated_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionDraftItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CheckedQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("checked_qty");

                    b.Property<int>("ConfirmedAttentionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirmed_attention_version");

                    b.Property<long>("DraftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("draft_id");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<long>("TaskItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_item_id");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "TaskId");

                    b.HasIndex("DraftId", "TaskItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_draft_items_draft_id_task_item_id");

                    b.HasIndex("TaskItemId", "TaskId");

                    b.ToTable("draft_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_draft_items_checked_qty_nonnegative", "checked_qty IS NULL OR checked_qty >= 0");

                            t.HasCheckConstraint("CK_draft_items_confirmed_attention_version_nonnegative", "confirmed_attention_version >= 0");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArrivalQtySnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("arrival_qty_snapshot");

                    b.Property<long>("BatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_id");

                    b.Property<int>("CheckedQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("checked_qty");

                    b.Property<DateOnly>("ExpiryDateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date_snapshot");

                    b.Property<long>("InspectionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inspection_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("ProductionDateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("production_date_snapshot");

                    b.Property<string>("StageSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("stage_snapshot");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BatchId", "ProductId");

                    b.HasIndex("InspectionId", "BatchId")
                        .IsUnique()
                        .HasDatabaseName("IX_inspection_items_inspection_id_batch_id");

                    b.HasIndex("InspectionId", "ProductId");

                    b.ToTable("inspection_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_items_arrival_qty_snapshot_nonnegative", "arrival_qty_snapshot >= 0");

                            t.HasCheckConstraint("CK_inspection_items_checked_qty_nonnegative", "checked_qty >= 0");

                            t.HasCheckConstraint("CK_inspection_items_stage_snapshot", "stage_snapshot IN ('discount_50', 'discount_20', 'withdraw', 'expired')");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionItemRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("InspectionItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inspection_item_id");

                    b.Property<int>("NewCheckedQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_checked_qty");

                    b.Property<int>("PreviousCheckedQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_checked_qty");

                    b.HasKey("Id");

                    b.HasIndex("InspectionItemId", "ChangedAtUtc", "Id")
                        .HasDatabaseName("IX_inspection_item_revisions_inspection_item_id_changed_at_utc_id");

                    b.ToTable("inspection_item_revisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_item_revisions_checked_qty_changed", "previous_checked_qty <> new_checked_qty");

                            t.HasCheckConstraint("CK_inspection_item_revisions_new_checked_qty_nonnegative", "new_checked_qty >= 0");

                            t.HasCheckConstraint("CK_inspection_item_revisions_previous_checked_qty_nonnegative", "previous_checked_qty >= 0");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InventoryAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AdjustedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("adjusted_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AdjustedStockQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adjusted_stock_qty");

                    b.Property<int>("ExcelStockQtySnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excel_stock_qty_snapshot");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "AdjustedAtUtc", "Id")
                        .HasDatabaseName("IX_inventory_adjustments_product_id_adjusted_at_utc_id");

                    b.ToTable("inventory_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_adjustments_adjusted_stock_qty_nonnegative", "adjusted_stock_qty >= 0");

                            t.HasCheckConstraint("CK_inventory_adjustments_excel_stock_qty_snapshot_nonnegative", "excel_stock_qty_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.LifecycleEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("BatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<long?>("SourceAdjustmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_adjustment_id");

                    b.Property<long?>("SourceImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_import_id");

                    b.Property<long?>("SourceInspectionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_inspection_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceAdjustmentId")
                        .HasDatabaseName("IX_lifecycle_events_source_adjustment_id");

                    b.HasIndex("SourceImportId")
                        .HasDatabaseName("IX_lifecycle_events_source_import_id");

                    b.HasIndex("SourceInspectionId", "ProductId")
                        .HasDatabaseName("IX_lifecycle_events_source_inspection_id_product_id");

                    b.HasIndex("ProductId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_lifecycle_events_product_id_occurred_at_utc_id");

                    b.HasIndex("BatchId", "ProductId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_lifecycle_events_batch_id_product_id_occurred_at_utc_id");

                    b.ToTable("lifecycle_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_lifecycle_events_event_type", "event_type IN ('product_stock_zero', 'batch_checked_zero', 'batch_tracking_resumed', 'task_auto_closed', 'draft_invalidated')");

                            t.HasCheckConstraint("CK_lifecycle_events_reason_not_blank", "length(reason) > 0 AND reason = trim(reason)");

                            t.HasCheckConstraint("CK_lifecycle_events_single_source", "(source_import_id IS NOT NULL) + (source_inspection_id IS NOT NULL) + (source_adjustment_id IS NOT NULL) <= 1");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("food")
                        .HasColumnName("category_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentBarcode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_barcode");

                    b.Property<string>("CurrentName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_name");

                    b.Property<int>("EffectiveStockQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_stock_qty");

                    b.Property<string>("EffectiveStockSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_stock_source");

                    b.Property<int>("ExcelStockQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excel_stock_qty");

                    b.Property<bool>("IsStockZeroTerminated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stock_zero_terminated");

                    b.Property<long?>("LastSeenImportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_import_id");

                    b.Property<int>("LifecycleGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lifecycle_generation");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("food_v1")
                        .HasColumnName("policy_code");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenImportId");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasDatabaseName("IX_products_product_code");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_category_code_not_blank", "length(trim(category_code)) > 0");

                            t.HasCheckConstraint("CK_products_effective_stock_qty_nonnegative", "effective_stock_qty >= 0");

                            t.HasCheckConstraint("CK_products_excel_stock_qty_nonnegative", "excel_stock_qty >= 0");

                            t.HasCheckConstraint("CK_products_policy_code_not_blank", "length(trim(policy_code)) > 0");

                            t.HasCheckConstraint("CK_products_product_code_not_blank", "length(product_code) > 0 AND product_code = trim(product_code)");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ProductTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_reason");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HighestStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("highest_stage");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ProductId")
                        .HasName("AK_tasks_id_product_id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_tasks_product_id_open")
                        .HasFilter("status = 'open'");

                    b.HasIndex("ProductId", "Status")
                        .HasDatabaseName("IX_tasks_product_id_status");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_tasks_closed_closed_at", "status = 'open' OR closed_at_utc IS NOT NULL");

                            t.HasCheckConstraint("CK_tasks_highest_stage", "highest_stage IN ('discount_50', 'discount_20', 'withdraw', 'expired')");

                            t.HasCheckConstraint("CK_tasks_open_closed_at", "status <> 'open' OR closed_at_utc IS NULL");

                            t.HasCheckConstraint("CK_tasks_status", "status IN ('open', 'completed', 'system_closed')");

                            t.HasCheckConstraint("CK_tasks_system_closed_reason", "status <> 'system_closed' OR (close_reason IS NOT NULL AND length(trim(close_reason)) > 0)");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ProductTaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttentionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attention_version");

                    b.Property<long>("BatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<bool>("RequiresReconfirmation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_reconfirmation");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "TaskId")
                        .HasName("AK_task_items_id_task_id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BatchId", "ProductId");

                    b.HasIndex("TaskId", "BatchId")
                        .IsUnique()
                        .HasDatabaseName("IX_task_items_task_id_batch_id");

                    b.HasIndex("TaskId", "ProductId");

                    b.ToTable("task_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_task_items_attention_version_nonnegative", "attention_version >= 0");

                            t.HasCheckConstraint("CK_task_items_requires_reconfirmation", "requires_reconfirmation IN (0, 1)");

                            t.HasCheckConstraint("CK_task_items_stage", "stage IN ('discount_50', 'discount_20', 'withdraw', 'expired')");
                        });
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Batch", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.ImportRecord", null)
                        .WithMany()
                        .HasForeignKey("LastSeenImportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StoreExpiryInspector.Domain.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ImportIssue", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.ImportRecord", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ImportWorkbook", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.ImportRecord", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Inspection", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.ProductTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionDraft", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.ProductTask", "Task")
                        .WithOne("Draft")
                        .HasForeignKey("StoreExpiryInspector.Domain.InspectionDraft", "TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionDraftItem", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.InspectionDraft", "Draft")
                        .WithMany("Items")
                        .HasForeignKey("DraftId", "TaskId")
                        .HasPrincipalKey("Id", "TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.ProductTaskItem", "TaskItem")
                        .WithMany("DraftItems")
                        .HasForeignKey("TaskItemId", "TaskId")
                        .HasPrincipalKey("Id", "TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionItem", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.Inspection", "Inspection")
                        .WithMany("Items")
                        .HasForeignKey("InspectionId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Inspection");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionItemRevision", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.InspectionItem", "InspectionItem")
                        .WithMany("Revisions")
                        .HasForeignKey("InspectionItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InspectionItem");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InventoryAdjustment", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.LifecycleEvent", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.InventoryAdjustment", null)
                        .WithMany()
                        .HasForeignKey("SourceAdjustmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StoreExpiryInspector.Domain.ImportRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceImportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StoreExpiryInspector.Domain.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StoreExpiryInspector.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("SourceInspectionId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Product", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.ImportRecord", null)
                        .WithMany()
                        .HasForeignKey("LastSeenImportId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ProductTask", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", "Product")
                        .WithMany("Tasks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ProductTaskItem", b =>
                {
                    b.HasOne("StoreExpiryInspector.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.Batch", "Batch")
                        .WithMany("TaskItems")
                        .HasForeignKey("BatchId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreExpiryInspector.Domain.ProductTask", "Task")
                        .WithMany("Items")
                        .HasForeignKey("TaskId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Batch", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Inspection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionDraft", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.InspectionItem", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ProductTask", b =>
                {
                    b.Navigation("Draft");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("StoreExpiryInspector.Domain.ProductTaskItem", b =>
                {
                    b.Navigation("DraftItems");
                });
#pragma warning restore 612, 618
        }
    }
}
